### ISSUE TITLE
Please add comments to your code

### ISSUE THREAD

**Issue by LeonardoAlchieri** [Paolo97Gll/Raytracer.jl#1]

**Comment by Paolo97Gll** [comment]
Specify better what you mean. The code presents docstrings for each function currently implemented in the package. Instead, the `main.jl` file is only a placeholder (for now): if you look inside it, you will notice that it is a very trivial hello world of about ten lines.

**Comment by Paolo97Gll** [comment]
Closing this issue since no response for a week. Feel free to reopen it if any problem arises.
