### ISSUE TITLE
Change name from `inverse` to `inv`

### ISSUE THREAD

**Issue by Samuele-Colombo** [Paolo97Gll/Raytracer.jl#12]
I suggest to change the name of the method defined [here](https://github.com/Paolo97Gll/Raytracer.jl/blob/87e8676adb023072355f4b4e259f1fd1b35c62a3/src/geometry.jl#L279) from `inverse` to `inv` to be coherent with the method `inv` used in type `Base.Matrix`.

**Comment by Paolo97Gll** [comment]
Should be already implemented by @Samuele-Colombo in #17 , can we close the issue?
