### ISSUE TITLE
Multi-Threading implementation

### ISSUE THREAD

**Issue by Paolo97Gll** [Paolo97Gll/Raytracer.jl#16]
Here an example of a multithreading version of `fire_all_rays!` function in `src/image_tracer.jl`:

```julia
Threads.@threads for ind ∈ indices
    ray = fire_ray(tracer, Tuple(ind)...)
    tracer.image.pixel_matrix[ind] = func(ray)
end
```

Do we need thread synchronization?

**Comment by Samuele-Colombo** [comment]
Data synchronization should be automatically dealt with by the `Threads.@treads` macro and there should be no data races in this loop. The real question is: do we really want to multithread this loop? I think we should wait and see where parallelization results in the best performance before committing to multithreading.

**Comment by Paolo97Gll** [comment]
Multithreading seems to have a low impact on the performance boost. A related discussion is in #19 about the `demo animation` command.

Here some new benchmarks of `fire_all_rays!` after #23.

1 thread: 38 seconds

```
(base) PS C:\Users\paolo\source\repos\Raytracer.jl> julia -t 1 raytracer_cli.jl demo image -r 2000:2000 -R Flat -o 0,0,50
  Activating environment at `C:\Users\paolo\source\repos\Raytracer.jl\Project.toml`

raytracer_cli.jl : Raytracer.jl demo image

Number of threads: 1

-> RENDERING
Loading scene... done!
Loading tracing informations... done!
Rendering image...
Progress: 100%|███████████████████████████████████████████████████████████████████████| Time: 0:00:38
Saving pfm image... done!

-> TONE MAPPING PROCESS
Loading input file 'demo.pfm'... done!
Applying tone mapping...  done!
Saving final image to 'demo.jpg'... done!
```

2 threads: 28 seconds

```
(base) PS C:\Users\paolo\source\repos\Raytracer.jl> julia -t 2 raytracer_cli.jl demo image -r 2000:2000 -R Flat -o 0,0,50
  Activating environment at `C:\Users\paolo\source\repos\Raytracer.jl\Project.toml`

raytracer_cli.jl : Raytracer.jl demo image

Number of threads: 2

-> RENDERING
Loading scene... done!
Loading tracing informations... done!
Rendering image...
Progress: 100%|███████████████████████████████████████████████████████████████████████| Time: 0:00:28
Saving pfm image... done!

-> TONE MAPPING PROCESS
Loading input file 'demo.pfm'... done!
Applying tone mapping...  done!
Saving final image to 'demo.jpg'... done!
```

4 threads: 30 seconds

```
(base) PS C:\Users\paolo\source\repos\Raytracer.jl> julia -t 4 raytracer_cli.jl demo image -r 2000:2000 -R Flat -o 0,0,50
  Activating environment at `C:\Users\paolo\source\repos\Raytracer.jl\Project.toml`

raytracer_cli.jl : Raytracer.jl demo image

Number of threads: 4

-> RENDERING
Loading scene... done!
Loading tracing informations... done!
Rendering image...
Progress: 100%|███████████████████████████████████████████████████████████████████████| Time: 0:00:30
Saving pfm image... done!

-> TONE MAPPING PROCESS
Loading input file 'demo.pfm'... done!
Applying tone mapping...  done!
Saving final image to 'demo.jpg'... done!
```

8 threads: 31 seconds

```
(base) PS C:\Users\paolo\source\repos\Raytracer.jl> julia -t 8 raytracer_cli.jl demo image -r 2000:2000 -R Flat -o 0,0,50
  Activating environment at `C:\Users\paolo\source\repos\Raytracer.jl\Project.toml`

raytracer_cli.jl : Raytracer.jl demo image

Number of threads: 8

-> RENDERING
Loading scene... done!
Loading tracing informations... done!
Rendering image...
Progress: 100%|███████████████████████████████████████████████████████████████████████| Time: 0:00:31
Saving pfm image... done!

-> TONE MAPPING PROCESS
Loading input file 'demo.pfm'... done!
Applying tone mapping...  done!
Saving final image to 'demo.jpg'... done!
```

**Comment by Samuele-Colombo** [comment]
On my machine results are actually quite similar. I find the following rendering times from the progress bar:

| threads | rendering time (speedup) | total execution time (speedup) |
|-----------:|----------------------------------:|-----------------------------------------:|
| 1           |                      27 s (    0%) |                              48 s     (0%)|
| 2           |                      19 s (~30%) |                              40 s (~17%)|
| 3           |                      17 s (~37%) |                              40 s (~17%)|
| 4           |                      15 s (~45%) |                              36 s (~25%)|
| 5           |                      15 s (~45%) |                              38 s (~20%)|
| 6           |                      16 s (~40%) |                              39 s (~19%)|
| 8           |                      16 s (~40%) |                              40 s (~17%)|
| 16         |                      23 s (~15%) |                              44 s  (~8%)|

There are some obvious machine related differences, but the optimal number of cores seems to be about 4

**Comment by Paolo97Gll** [comment]
With path tracer implementation in #20 seems to work
