### ISSUE TITLE
No way for user to specify average luminosity in tonemapping

### ISSUE THREAD

**Issue by Samuele-Colombo** [Paolo97Gll/Raytracer.jl#30]
As it can be seen [here](https://github.com/Paolo97Gll/Raytracer.jl/blob/c846d454cff2bfc5061ac3a9385b90bb03b1d8b2/src/user_utils.jl#L23-L38) there is no way for the user to specify a custom value for luminosity during image normalization in tonemapping. This option is often essential to obtain decent images. We should add this option to the High Level API and the CLI before release.

**Comment by Paolo97Gll** [comment]
Implemented in commit [5344061](https://github.com/Paolo97Gll/Raytracer.jl/commit/5344061a838e7e8c2644b7de599972568faa5e3b)
